### ISSUE TITLE
Add Default Front Matter to new drafts

### ISSUE THREAD

**Issue by thexavismith** [smithtimmytim/brightpixels.blog#21]
#### Description

I constantly forget all the stuff I need to add to a post… ugh. Is Jekyll not working for me anymore? Anyway, here's the default stuff I need:

```yaml
seo_title:
subtitle:
custom_type:
link_url:
categories:
review:
  type:
  rating:
  movie:
    letterboxd:
excerpt:
featured_image:
is_rss_only:
```
